# Generated by Django 4.2.5 on 2023-10-30 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_thread_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='article',
        ),
        migrations.CreateModel(
            name='ArticleThreads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.article')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='api.thread')),
            ],
        ),
    ]
