# Generated by Django 4.2.6 on 2023-10-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_thread_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_preview',
            field=models.TextField(blank=True),
        ),
    ]
