# Generated by Django 4.2.5 on 2023-10-30 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_thread_article_articlethreads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlethreads',
            name='thread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='api.thread'),
        ),
    ]
