# Generated by Django 4.2.5 on 2023-10-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_articlethreads_thread'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleThreads',
            new_name='ArticleThread',
        ),
    ]
