# Generated by Django 4.2.6 on 2023-10-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_articlethread_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_preview',
            field=models.TextField(blank=True),
        ),
    ]
