# Generated by Django 4.2.6 on 2023-10-31 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_article_content_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_preview',
        ),
    ]
