# Generated by Django 4.2.7 on 2023-12-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_articlevote'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articlevote',
            constraint=models.UniqueConstraint(fields=('voter', 'article'), name='unique_article_voter'),
        ),
    ]
