version: '3.8'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django_server
    environment:
      - DATABASE_URL
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - pubnetwork
    depends_on:
      database:
        condition: service_started

  frontend:
    build: ./frontend
    command: npm run dev
    container_name: client_server
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_started

  database:
    container_name: database_server
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'thepub'
      MYSQL_ROOT_PASSWORD: 'rootpw'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./my-db:/var/lib/mysql
    networks:
      - pubnetwork
    hostname: pubdatabase

networks:
  pubnetwork:
    name: pubnetwork