# Generated by Django 4.2.5 on 2023-09-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('content', models.TextField(blank=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('last_edited', models.DateField(auto_now=True)),
            ],
        ),
    ]
