@username = jacegonzales25
@password = JaceGonzales25!
@firstName = Jace
@lastName = Gonzales
@email = jacegonzales25@gmail.com
@host = http://localhost:8000

### ========================= Authentication =========================
### Sign up
POST {{host}}/auth/signup/
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}",
  "confirmed_password": "{{password}}",
  "email": "{{email}}"
}

### Login
# @name postLogin
POST {{host}}/auth/login/
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}


### Save token
@token = {{postLogin.response.body.token}}
### ========================= Authentication =========================

### ========================= Account / Profile actions =========================
### Log out
GET {{host}}/auth/logout/
Content-Type: application/json
Authorization: Bearer {{token}}

### Get certain user profile
GET {{host}}/api/sebastian/
Content-Type: application/json

### Get current user profile
GET {{host}}/api/{{username}}/
Content-Type: application/json

### Get current user account settings
GET {{host}}/settings/account/
Content-Type: application/json
Authorization: Bearer {{token}}

### Get current user profile settings
GET {{host}}/settings/profile/
Content-Type: application/json
Authorization: Bearer {{token}}

### Change password of current user
PUT {{host}}/settings/change-password/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "current_password": "",
  "new_password": "",
  "confirmed_new_password": ""
}


### Update user profile
PUT {{host}}/settings/profile/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "is_active": false,
  "profile_picture": "https://api.dicebear.com/7.x/notionists-neutral/svg?seed=ABCDE",
  "bio": "lorem",
  "preferred_tags": [
    "c++"
  ]
}

### Follow a user
GET {{host}}/api/follow/sebastian/
Content-Type: application/json
Authorization: Bearer {{token}}

### Unfollow a user
DELETE {{host}}/api/follow/sebastian/
Content-Type: application/json
Authorization: Bearer {{token}}
### ========================= Account / Profile actions =========================

### ========================= Content actions ========================= 
### Get articles
GET {{host}}/api/articles/
Content-Type: application/json

### Get user articles
GET {{host}}/api/{{username}}/articles/
Content-Type: application/json

### Create article
### tags is an optional field. you don't have to provide an empty array
### if you want no tags
# @name postArticle
POST {{host}}/api/{{username}}/articles/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "A title",
    "content": "Some content",
    "tags": [
        "health",
        "meditation"
    ]
}

### ID of created article
@articleId = {{postArticle.response.body.id}}
@articleUrl = {{postArticle.response.body.url}}

### Retrieve article
### Authorization is optional.
GET {{host}}/api/jacegonzales25/20-A%20title/
Content-Type: application/json
Authorization: Bearer {{token}}

### Update article
### tags is an optional field. if you don't provide
### an array of tags, it will assume you don't want to update it
PUT {{host}}{{postArticle.response.body.url}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "New title!!!!!",
    "content": "New content!!!!!",
    "tags": 1
}

### Delete article
DELETE {{host}}{{articleUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Get threads
GET {{host}}/api/threads/
Content-Type: application/json

### Create thread associated with article
# @name postArticleThread
POST {{host}}/api/threads/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "article": {{articleId}},
    "content": "A thread associated with an article"
}

### Aricle associated Thread ID
@postArticleThreadId = {{postArticleThread.response.body.id}}

### Create standalone thread
# @name postStandaloneThread
POST {{host}}/api/threads/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "A standalone thread"
}

### Standalone thread ID
@standaloneThreadId = {{postStandaloneThread.response.body.id}}

### Create subthread
POST {{host}}/api/threads/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "parent": {{standaloneThreadId}},
    "content": "A standalone thread"
}

# Some bug happening when using variables here
# Just replace "raymond3/19-A%20title" with
# appropriate article url
### Upvote article
PUT {{host}}/api/jacegonzales25/20-A%20title/vote/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "is_upvote": true
}

### Downvote article
PUT {{host}}/api/jacegonzales25/20-A%20title/vote/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "is_upvote": false
}

### Delete vote
DELETE {{host}}/api/jacegonzales25/20-A%20title/vote/
Content-Type: application/json
Authorization: Bearer {{token}}
### ========================= Content actions ========================= 