# Generated by Django 4.2.5 on 2023-10-05 12:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(default=core.models.generate_random_default_profile_picture),
        ),
    ]
