# Generated by Django 4.2.5 on 2023-10-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_follow_follower'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='unique_follower'),
        ),
    ]
